pipeline {
    agent any

    stages {
        stage('Docker build') {
            steps {
                script {
                    sh "docker build -f pipelineDockerHub/Dockerfile -t medyesus/dokerhubtest:1.0.0-${BUILD-ID} pipelineDockerHub"
                }
            }
        }
        stage('Docker push') {
            steps {
                script {
                    sh "docker push medyesus/dokerhubtest:1.0.0-${BUILD-ID}"
                }
            }
        }
    }
}
