pipeline {
    agent any

    stages {
        stage('Docker build') {
            steps {
                script {
                    sh "docker build -f pipelineDockerHub/Dockerfile -t medyesus/dokerhubtest:1.0.0-${BUILD_ID} pipelineDockerHub"
                }
            }
        }
        stage('Docker push') {
            steps {
                script {
                  withCredentials([usernamePassword(credentialsId: 'dockerhub_credentials', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                    sh "docker login -u ${env.DOCKERHUB_USERNAME} -p ${env.DOCKERHUB_PASSWORD}"
                    sh "docker push medyesus/dokerhubtest:1.0.0-${BUILD_ID}"
                  }
                }
            }
        }   
        stage('Paso final') {
            steps {
                echo 'Hello World'
            }
        }     
    }
    post {
      always {
        echo "Let's see how it went..."
      }
      success {
        echo "It was a success!"
      }
      failure{
        echo "It was a failure :("
      }
    }
}
