pipeline {
    agent any

    stages {
        stage('Paso 1') {
            steps {
                echo 'Hello World'
            }
        }
    }
    post {
      always {
        echo "Let's see how it went.."
      }
      success {
        echo "It was a success!"
      }
      failure{
        echo "It was a failure :("
      }
    }

}
